### ISSUE TITLE
ORACLE数据库，出现标识符过长的异常

### ISSUE THREAD

**Issue by chenhahacjl** [zhontai/Admin.Core#7]
用ORACLE数据库的时候，会出现标识符过长的异常。

Unhandled exception. System.Exception: ORA-00972: 标识符过长
ORA-06512: 在 line 26
 ---> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00972: 标识符过长
ORA-06512: 在 line 26
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at FreeSql.Internal.CommonProvider.AdoProvider.ExecuteNonQuery(DbConnection connection, DbTransaction transaction, CommandType cmdType, String cmdText, DbParameter[] cmdParms)
   --- End of inner exception stack trace ---
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(TypeAndName[] objects)
   at FreeSql.Internal.CommonProvider.CodeFirstProvider.SyncStructure(Type[] entityTypes)
   at Admin.Core.Db.DbHelper.SyncStructure(IFreeSql db, String msg, DbConfig dbConfig) in D:\GitFolder\Admin.Core\Admin.Core\Db\DbHelper.cs:line 71
   at Admin.Core.Db.ServiceCollectionExtensions.AddDb(IServiceCollection services, IHostEnvironment env, AppConfig appConfig) in D:\GitFolder\Admin.Core\Admin.Core\Db\ServiceCollectionExtensions.cs:line 58
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by zhontai** [comment]
可加群反馈一下Oracle的使用情况
